### ISSUE TITLE
license

### ISSUE THREAD

**Issue by waldenn** [OwenK2/Interactive-Map-Quiz#1]
Hi Owen, love your geo-quiz app! Very well done. Could you please add a license for your project?
If its opensource I might be able to integrate it into my Conzept project at a later stage. Thanks!

**Comment by OwenK2** [comment]
Hello @waldenn I just added a license. Here are the details: http://creativecommons.org/licenses/by-nc-sa/4.0/. Thank you for your patience

**Comment by waldenn** [comment]
Thanks!
