### ISSUE TITLE
request: add states/provinces

### ISSUE THREAD

**Issue by pljvp** [OwenK2/Interactive-Map-Quiz#2]
I tried to cheat your code and replace the contents of countries.geojson with contents of this provincies.geojson (containing data of 'regions' or states within the Netherlands):
https://www.webuildinternet.com/articles/2015-07-19-geojson-data-of-the-netherlands/provinces.geojson
( I changed "name" into "id", matching the countries.geojson).

![image](https://github.com/user-attachments/assets/44ddd2d7-8398-4f61-96a2-187c10b1ae56)
The province outlines are visible, but the zooming does not work anymore and also the question still states 'country names' not 'province names'.

An import function for of such provinces.geojson provinces-main-cities or perhaps even rivers would be very nice.

**Comment by OwenK2** [comment]
Very cool, yeah this is something I've wanted to come back to and re-code it to be super flexible. That way it could be used for not just countries, but rivers, mountains, famous locations etc.

If I get inspired hopefully I can come back to this project, if you take a swing at it, please let me know!

**Comment by pljvp** [comment]
See https://wereldopener.nl/geo/
Zooming doesnt work yet, and I have to select EU and de-select isRecognized:
![image](https://github.com/user-attachments/assets/c5de2547-8ae1-4d41-852c-6c51396ca864)
![image](https://github.com/user-attachments/assets/c44c6cc4-57f0-4ae4-8d4f-9b6c51f80fa4)
![image](https://github.com/user-attachments/assets/0d2f212c-6d0f-4691-9819-accceadaf244)

But I get some weird crash - randomly during quizing. Cant identify it to my adjusted geojsons. 
[geojsons.zip](https://github.com/user-attachments/files/17608663/geojsons.zip)

That was my first thought.

**Comment by pljvp** [comment]
Got basics working:
- Fixed geojsons (one missing ID and a missing name)
[geojsons_fixed.zip](https://github.com/user-attachments/files/17610152/geojsons_fixed.zip)

- Updated checks, selecting only Europe
- Disabled 'shape' option in main menu
